### ISSUE TITLE
C/C++ Implementation

### ISSUE THREAD

**Issue by yuguang** [yuguang/kruskal-sparse#5]
We need a faster implementation so that the largest test graphs from http://www.math.uwaterloo.ca/~bico/co759/spanning/ run in a few seconds.

**Comment by sjbrunst** [comment]
I've written an implementation for the tnode class, but this is my first time writing C++ code in two years, so feel free to make changes.

**Comment by ibdimock** [comment]
I've written the code to read in the node/edge data and also sort the edges.

**Comment by ibdimock** [comment]
I've finished up implementation of Kruskal's algorithm and included some timing code. I've verified the output on all but the largest graph.
